name: Reflect changes in the cu118 branch

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  merge_cu118:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: cuda118
          fetch-depth: 0
      - uses: fregante/setup-git-user@v2
      - name: print branches and status
        run: git branch && git status
      - name: rebase cu118 onto main
        run: git rebase origin/main
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: cuda118
          force_with_lease: true

