
name: Testing and docs

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: run tests
        run: make .make/run-tests
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
          env: "CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}"


