
name: Tests

on:
  push:
    branches: ["main", "cu12"]
  pull_request:
    branches: ["main", "cu12"]

permissions:
  contents: read

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: 'poetry'
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: install dependencies
        run: make .make/deps .make/test-deps
      - name: run tests
        run: make .make/run-tests
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          verbose: true
      - name: Build package
        run: poetry build
      - name: save package
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
  publish:
    runs-on: ubuntu-latest
    needs: test_and_build
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/ot_markov_distances
    # to only publish if there is a tag release
    # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    if: ${{ github.repository_owner == 'YusuLab' }}
    steps:
      - name: retrieve package
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: list files
        run: find
      - name: publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
