
name: Tests

on:
  push:
    branches: ["main", "cu12"]
  pull_request:
    branches: ["main", "cu12"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: install dependencies
        run: make .make/deps .make/test-deps
      - name: run tests
        run: make .make/run-tests
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          verbose: true
      - name: Build package
        run: poetry build
      - name: publish package
        run: poetry publish
